RAW_DATABASE="base_info"
HIVE_DB=model
HIVE_TABLE=
MYCAT_TABLE=
HIVE_COLUMNS=""

#班级信息表
HIVE_TABLE_BASE_CLASS_INFO=base_class_info
MYCAT_TABLE_BASE_CLASS_INFO=base_class_info

#专业信息表
HIVE_TABLE_BASE_MAJOR_INFO=base_major_info
MYCAT_TABLE_BASE_MAJOR_INFO=base_major_info

#学院信息表
HIVE_TABLE_BASE_ACADEMY_INFO=base_academy_info
MYCAT_TABLE_BASE_ACADEMY_INFO=base_academy_info

#区域信息
HIVE_TABLE_BASE_AREA_INFO=base_area_info
MYCAT_TABLE_BASE_AREA_INFO=base_area_info

#学院专业班级信息表
HIVE_TABLE_BASE_CLASS_MAJOR_INFO=base_class_major_info
MYCAT_TABLE_BASE_CLASS_MAJOR_INFO=base_class_major_info

#年级表
HIVE_TABLE_BASE_GRADE_INFO=base_grade_info
MYCAT_TABLE_BASE_GRADE_INFO=base_grade

#学期
HIVE_TABLE_SEMESTER_INFO=base_semester_info
MYCAT_TABLE_SEMESTER_INFO=base_semester_info

#高基表院系情况信息
HIVE_TABLE_ANALYSIS_ACADEMY_INFO=analysis_academy_info
MYCAT_TABLE_ANALYSIS_ACADEMY_INFO=analysis_academy_info

#高基表专业情况
HIVE_TABLE_ANALYSIS_MAJOR_INFO=analysis_major_info
MYCAT_TABLE_ANALYSIS_MAJOR_INFO=analysis_major_info



